# Generated by Django 3.2.20 on 2023-08-14 22:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saves', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='save',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='save',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
