# Generated by Django 3.2.20 on 2023-08-15 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
        ('saves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='stories.story'),
        ),
    ]
