# Generated by Django 3.2.20 on 2023-08-23 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=50)),
                ('activities', models.TextField(blank=True, max_length=800)),
                ('priority', models.IntegerField(choices=[(1, 'Now'), (2, 'Soon'), (3, 'Within 3 years'), (4, 'Within 5 years'), (5, 'Might happen')], default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('story_tag', models.ManyToManyField(blank=True, to='saves.Save')),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
    ]
