# Generated by Django 3.2.20 on 2023-08-15 18:48

import destinations.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saves', '0001_initial'),
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='story_tag',
            field=models.ForeignKey(blank=True, default=destinations.models.DefaultStoryTag, on_delete=django.db.models.deletion.CASCADE, to='saves.save'),
        ),
    ]
