# Generated by Django 3.2.20 on 2023-08-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saves', '0001_initial'),
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='story_tag',
        ),
        migrations.AddField(
            model_name='destination',
            name='story_tag',
            field=models.ManyToManyField(blank=True, to='saves.Save'),
        ),
    ]
