# Generated by Django 3.2.20 on 2023-08-15 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saves', '0002_alter_save_story'),
        ('destinations', '0002_alter_destination_story_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='story_tag',
            field=models.ForeignKey(blank=True, default=('No story tag', 'No story tag'), on_delete=django.db.models.deletion.CASCADE, to='saves.save'),
        ),
    ]
